[build-system]
requires = ["scikit-build-core >=0.10", "pybind11 == 2.10.1"]
#requires = ["scikit-build-core >=0.10", "nanobind >= 2.0.0"]
build-backend = "scikit_build_core.build"

[project]
name = "rhino3dm"
version = "8.17.2"
description = "CGAL wrapper for COMPAS."
#readme = "README.md"
requires-python = ">=3.9"
authors = [
    { name = "ee", email = "ffff@gmail.com" },
    { name = "dd", email = "ffff@gmail.com" },
]
classifiers = [
    "License :: OSI Approved :: GNU Lesser General Public License v3 (LGPLv3)",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: Implementation :: CPython",
    "Development Status :: 4 - Beta",
]

[tool.scikit-build]
minimum-version = "build-system.requires"
build-dir = "build/{wheel_tag}"
wheel.packages = ["rhino3dm"]
cmake.version = ">=3.15"
cmake.build-type = "Release"
#cmake.args = ["-DPYTHON_BINDING_LIB=NANOBIND"]

#[tool.scikit-build.editable]
#mode = "redirect"
#verbose = true
#rebuild = true


# pip install -e . --config-settings editable=true
