from typing import Iterable, List
from uuid import UUID


class File3dm:
    @property
    def StartSectionComments(self) -> str: ...
    @property
    def ApplicationName(self) -> str: ...
    @property
    def ApplicationUrl(self) -> str: ...
    @property
    def ApplicationDetails(self) -> str: ...
    @property
    def CreatedBy(self) -> str: ...
    @property
    def LastEditedBy(self) -> str: ...
    @property
    def Revision(self) -> int: ...
    @property
    def Settings(self) -> File3dmSettings: ...
    @property
    def Objects(self) -> File3dmObjectTable: ...
    @property
    def Materials(self) -> Iterable[Material]: ...
    @property
    def Layers(self) -> Iterable[Layer]: ...
    @property
    def DimStyles(self) -> Iterable[DimensionStyle]: ...
    @property
    def InstanceDefinitions(self) -> Iterable[InstanceDefinitionGeometry]: ...
    @property
    def Views(self) -> Iterable[ViewInfo]: ...
    @property
    def NamedViews(self) -> Iterable[ViewInfo]: ...
    @property
    def PlugInData(self) -> File3dmPlugInDataTable: ...
    @property
    def Strings(self) -> File3dmStringTable: ...
    @staticmethod
    def Read(path: str) -> File3dm: ...
    @staticmethod
    def ReadNotes(path: str) -> str: ...
    @staticmethod
    def ReadArchiveVersion(path: str) -> int: ...
    @staticmethod
    def FromByteArray(bytes: List[byte]) -> File3dm: ...
    def Write(self, path: str, version: int) -> bool: ...


class Layer:
    """Python wrapper for the openNURBS `ON_Layer` class.
    """
    def __init__(self) -> None: ...
    def __repr__(self) -> str: ...

    @property
    def color(self) -> tuple[int, int, int, int]: ...
    @color.setter
    def color(self, color: tuple[int, int, int, int]) -> None: ...

    @property
    def full_path(self) -> str: ...

    @property
    def iges_level(self) -> int: ...
    @iges_level.setter
    def iges_level(self, level: int) -> None: ...

    @property
    def index(self) -> int: ...
    @index.setter
    def index(self, index: int) -> None: ...

    @property
    def is_expanded(self) -> bool: ...
    @is_expanded.setter
    def is_expanded(self, is_expanded: bool) -> None: ...

    @property
    def is_locked(self) -> bool: ...
    @is_locked.setter
    def is_locked(self, is_locked: bool) -> None: ...

    @property
    def is_visible(self) -> bool: ...
    @is_visible.setter
    def is_visible(self, is_visible: bool) -> None: ...

    @property
    def layer_uuid(self) -> UUID: ...
    @layer_uuid.setter
    def layer_uuid(self, layer_uuid: UUID) -> None: ...

    @property
    def line_type_index(self) -> int: ...
    @line_type_index.setter
    def line_type_index(self, index: int) -> None: ...

    @property
    def name(self) -> str: ...
    @name.setter
    def name(self, name: str) -> None: ...

    @property
    def path_separator(self) -> str: ...

    @property
    def parent_uuid(self) -> UUID: ...
    @parent_uuid.setter
    def parent_uuid(self, parent_uuid: UUID) -> None: ...

    @property
    def persistent_locking(self) -> bool: ...
    @persistent_locking.setter
    def persistent_locking(self, persistent_locking: bool) -> None: ...

    @property
    def persistent_visibility(self) -> bool: ...
    @persistent_visibility.setter
    def persistent_visibility(self, persistent_visibility: bool) -> None: ...

    @property
    def plot_color(self) -> tuple[int, int, int, int]: ...
    @plot_color.setter
    def plot_color(self, plot_color: tuple[int, int, int, int]) -> None: ...

    @property
    def plot_weight(self) -> float: ...
    @plot_weight.setter
    def plot_weight(self, plot_weight: float) -> None: ...

    @property
    def render_material_index(self) -> int: ...
    @render_material_index.setter
    def render_material_index(self, index: int) -> None: ...


class LayerView:
    """Python wrapper for the openNURBS `ON_Layer` class, after being added to a 3dm
    model, i.e., being immutable.
    """
    def __repr__(self) -> str: ...

    @property
    def color(self) -> tuple[int, int, int, int]: ...

    @property
    def full_path(self) -> str: ...

    @property
    def iges_level(self) -> int: ...

    @property
    def is_expanded(self) -> bool: ...

    @property
    def is_locked(self) -> bool: ...

    @property
    def is_visible(self) -> bool: ...

    @property
    def layer_uuid(self) -> UUID: ...

    @property
    def line_type_index(self) -> int: ...

    @property
    def name(self) -> str: ...

    @property
    def path_separator(self) -> str: ...

    @property
    def parent_uuid(self) -> UUID: ...

    @property
    def persistent_locking(self) -> bool: ...

    @property
    def persistent_visibility(self) -> bool: ...

    @property
    def plot_color(self) -> tuple[int, int, int, int]: ...

    @property
    def plot_weight(self) -> float: ...

    @property
    def render_material_index(self) -> int: ...


class LayerTable:
    def AddLayer(self, name: str, color: tuple[int, int, int, int]) -> int: ...
    def FindName(self, name: str, parentId: UUID) -> Layer: ...
    def FindIndex(self, index: int) -> Layer: ...
