"""
Type hints
----------


__author__ = "Studio W Engineers"

__version__ = "0.1.0"

__maintainer__ = "Studio W Engineers"

__email__ = "studio.w.engineers@gmail.com"

__status__ "Release"
"""
# standard library imports
from typing import Iterator
from uuid import UUID

# third party library imports

# local library specific imports


class Layer:
    """Python wrapper for the openNURBS `ON_Layer` class.
    """
    def __init__(self) -> None: ...
    def __repr__(self) -> str: ...

    @property
    def color(self) -> tuple[int, int, int, int]: ...
    @color.setter
    def color(self, color: tuple[int, int, int, int]) -> None: ...

    @property
    def full_path(self) -> str: ...

    @property
    def iges_level(self) -> int: ...
    @iges_level.setter
    def iges_level(self, level: int) -> None: ...

    @property
    def index(self) -> int: ...

    @property
    def is_expanded(self) -> bool: ...
    @is_expanded.setter
    def is_expanded(self, is_expanded: bool) -> None: ...

    @property
    def is_locked(self) -> bool: ...
    @is_locked.setter
    def is_locked(self, is_locked: bool) -> None: ...

    @property
    def is_visible(self) -> bool: ...
    @is_visible.setter
    def is_visible(self, is_visible: bool) -> None: ...

    @property
    def layer_uuid(self) -> UUID: ...
    @layer_uuid.setter
    def layer_uuid(self, layer_uuid: UUID) -> None: ...

    @property
    def line_type_index(self) -> int: ...
    @line_type_index.setter
    def line_type_index(self, index: int) -> None: ...

    @property
    def name(self) -> str: ...
    @name.setter
    def name(self, name: str) -> None: ...

    @property
    def path_separator(self) -> str: ...

    @property
    def parent_uuid(self) -> UUID: ...
    @parent_uuid.setter
    def parent_uuid(self, parent_uuid: UUID) -> None: ...

    @property
    def persistent_locking(self) -> bool: ...
    @persistent_locking.setter
    def persistent_locking(self, persistent_locking: bool) -> None: ...

    @property
    def persistent_visibility(self) -> bool: ...
    @persistent_visibility.setter
    def persistent_visibility(self, persistent_visibility: bool) -> None: ...

    @property
    def plot_color(self) -> tuple[int, int, int, int]: ...
    @plot_color.setter
    def plot_color(self, plot_color: tuple[int, int, int, int]) -> None: ...

    @property
    def plot_weight(self) -> float: ...
    @plot_weight.setter
    def plot_weight(self, plot_weight: float) -> None: ...

    @property
    def render_material_index(self) -> int: ...
    @render_material_index.setter
    def render_material_index(self, index: int) -> None: ...


class LayerView:
    """Python wrapper for the openNURBS `ON_Layer` class, after being added to a 3dm
    model, i.e., being immutable.
    """
    def __repr__(self) -> str: ...

    @property
    def color(self) -> tuple[int, int, int, int]: ...

    @property
    def full_path(self) -> str: ...

    @property
    def iges_level(self) -> int: ...

    @property
    def index(self) -> int: ...

    @property
    def is_expanded(self) -> bool: ...

    @property
    def is_locked(self) -> bool: ...

    @property
    def is_visible(self) -> bool: ...

    @property
    def layer_uuid(self) -> UUID: ...

    @property
    def line_type_index(self) -> int: ...

    @property
    def name(self) -> str: ...

    @property
    def path_separator(self) -> str: ...

    @property
    def parent_uuid(self) -> UUID: ...

    @property
    def persistent_locking(self) -> bool: ...

    @property
    def persistent_visibility(self) -> bool: ...

    @property
    def plot_color(self) -> tuple[int, int, int, int]: ...

    @property
    def plot_weight(self) -> float: ...

    @property
    def render_material_index(self) -> int: ...


class LayerTable:
    def __getitem__(self, index: int) -> LayerView:...

    def __iter__(self) -> Iterator[LayerView]: ...

    def __len__(self) -> int: ...

    def add(self, layer: Layer) -> int: ...

    def count(self) -> int: ...

    def delete_by_name(self, layer_name: str) -> bool: ...

    def delete_by_uuid(self, layer_uuid: UUID) -> bool: ...

    def get_by_index(self, layer_index: int) -> LayerView: ...

    def get_by_name(self, layer_name: str) -> LayerView: ...

    def get_by_uuid(self, layer_uuid: UUID) -> LayerView: ...

    def get_layer_index(self, full_name: str) -> int: ...

    def get_layer_uuid(self, full_name: str) -> UUID: ...

    def has(self, layer_name: str) -> bool: ...

    def max_index(self) -> int: ...

    def replace(self, layer_to_be_replaced: str, new_layer: Layer) -> bool: ...


class Model:
    def __init__(self) -> None: ...

    def write(self, path: str, version: int = 7) -> bool: ...

    @property
    def LayerTable(self) -> LayerTable: ...

    @staticmethod
    def read(path: str) -> Model: ...

    @staticmethod
    def read_archive_version(path: str) -> int: ...

    @staticmethod
    def read_notes(path: str) -> str: ...


class Point:
    def __add__(self, other: Point) -> Point: ...

    def __eq__(self, other: object) -> bool: ...

    def __init__(self, x: float, y: float, z: float) -> None: ...

    def __mul__(self, other: float) -> Point: ...

    def __ne__(self, other: object) -> bool: ...

    @property
    def x(self) -> float: ...
    @x.setter
    def x(self, value: float) -> None: ...

    @property
    def y(self) -> float: ...
    @y.setter
    def y(self, value: float) -> None: ...

    @property
    def z(self) -> float: ...
    @z.setter
    def z(self, value: float) -> None: ...
