name: workflow ci
on: [push]

jobs:

  #checks if build scripts have changed
  check_build_scripts:
    name: check build scripts and tools
    runs-on: ubuntu-latest
    outputs:
      any_changed: ${{ steps.changed-files.outputs.any_changed }}
    steps:
      - name: checkout
        uses: actions/checkout@v4.1.1
        with:
          fetch-depth: 2
      - name: check changed files
        uses: tj-actions/changed-files@v45.0.4
        id: changed-files
        with:
          files: |
            .github/workflows/workflow_ci.yml
            Current_Development_Tools.md
            script/**
            src/CMakeLists.txt
            src/librhino3dm_native/CMakeLists.txt
      - name: List all changed files
        env:
          ALL_CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
        run: |
          for file in ${ALL_CHANGED_FILES}; do
            echo "$file was changed"
          done

  check_tests_py:
    name: check if py tests changed
    runs-on: ubuntu-latest
    outputs:
      any_changed: ${{ steps.changed-files.outputs.any_changed }}
    steps:
      - name: checkout
        uses: actions/checkout@v4.1.1
        with:
          fetch-depth: 2
      - name: check changed files
        uses: tj-actions/changed-files@v45.0.4
        id: changed-files
        with:
          files: |
            tests/python/**
      - name: List all changed files
        env:
          ALL_CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
        run: |
          for file in ${ALL_CHANGED_FILES}; do
            echo "$file was changed"
          done

  #checks if src/bindings have changed
  check_bindings:
    name: check src/bindings
    runs-on: ubuntu-latest
    outputs:
      any_changed: ${{ steps.changed-files.outputs.any_changed }}
    steps:
      - name: checkout
        uses: actions/checkout@v4.1.1
        with:
          fetch-depth: 2
      - name: check changed files
        uses: tj-actions/changed-files@v45.0.4
        id: changed-files
        with:
          files: |
            src/bindings/**
            src/CMakeLists.txt
      - name: List all changed files
        env:
          ALL_CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
        run: |
          for file in ${ALL_CHANGED_FILES}; do
            echo "$file was changed"
          done

  build_py_all_bdist:
    name: build python ${{ matrix.python-version }} ${{ matrix.target }} ${{ matrix.os }} bdist
    runs-on: ${{ matrix.os }}
    needs: [check_bindings, check_build_scripts, check_tests_py]
    if: ${{ needs.check_bindings.outputs.any_changed == 'true' || needs.check_build_scripts.outputs.any_changed == 'true' || needs.check_tests_py.outputs.any_changed == 'true' }}
    strategy:
      matrix:
        os: [windows-2022]
        python-version: ["3.12", "3.13"]
        include:
          - os: windows-2022
            target: windows
      fail-fast: false
    steps:
      - name: set up python ${{ matrix.python-version }}
        uses: actions/setup-python@v5.4.0
        with:
          python-version: ${{ matrix.python-version }}
      - name: info
        run: python --version && cmake --version
      - name: install dependencies
        run: python -m pip install --upgrade pip setuptools wheel
      - name: install dependencies 2
        run: python -m pip install packaging
      - name: checkout
        uses: actions/checkout@v4.1.1
      - name: update submodules
        run: git submodule update --init --recursive
      - name: build python ${{ matrix.python-version }} ${{ matrix.os }}
        run: python setup.py bdist_wheel build --debug
      - name: artifacts
        uses: actions/upload-artifact@v4.3.1
        with:
          path: dist
          name: rhino3dm.py ${{ matrix.python-version }} ${{ matrix.os }}

  test_python_bdist:
    name: test py ${{ matrix.python-version }} ${{ matrix.target }} ${{ matrix.os }} bdist
    runs-on: ${{ matrix.os }}
    needs: [build_py_all_bdist]
    strategy:
      matrix:
        os: [windows-2022]
        python-version: ["3.12", "3.13"]
        include:
          - os: windows-2022
            target: windows
      fail-fast: false
    steps:
    - name: set up python ${{ matrix.python-version }}
      uses: actions/setup-python@v5.4.0
      with:
        python-version: ${{ matrix.python-version }}
    - name: info
      run: python --version && cmake --version
    - name: checkout
      uses: actions/checkout@v4.1.1
    - name: download artifact
      uses: actions/download-artifact@v4.1.7
      with:
        name: rhino3dm.py ${{ matrix.python-version }} ${{ matrix.os }}
        path: tests/python/lib
    - name: install whl
      shell: bash
      run: pip install --no-index tests/python/lib/*.whl --force-reinstall
    - name: test python bdist
      run: |
        cd tests/python
        python -m unittest discover .
